### ISSUE TITLE
Add commit name check via GitHub Actions

### ISSUE THREAD

**Issue by SSSKrut** [butvinm/nobutt#14]
The suggested commit name design here:
`<branch-id>: <commit-name>`

So issue #1 will have commits like this (on branch _1-issue-fix_ for example):

```
1: Chore main.py
1: Fix script.sh
1: Add note to README.md 
```

**Comment by butvinm** [comment]
@SSSKrut Is it `issue-id` , not `branch-id`?

**Comment by SSSKrut** [comment]
> @SSSKrut Is it `issue-id` , not `branch-id`?

Actually, it's impossible to add check for branch or issue exactly. Because after PR there will no be such branch and it will produce errors. So I don't know is it really necessary to control similarity of branch-id, issue-id and number in commit's name
